#!/bin/bash
# Assembles the ONE app artifact at dist/memterm.app from a stamped release
# binary: Contents/MacOS/memterm, Contents/Resources/memterm.icns, Info.plist
# carrying real version numbers, ad-hoc codesign. Prints the .app path last.
#
# TESTING.md §3.1/§3.2 (bug 5 regression — dirty debug builds presented as
# artifact evidence):
#   * refuses a dirty working tree unless MEMTERM_ALLOW_DIRTY=1, and a forced
#     dirty build is ALWAYS stamped "-dirty" — it can never satisfy the
#     verify.sh identity check.
#   * generates Sources/memterm/BuildStamp.generated.swift (gitignored) and
#     compiles with -DMEMTERM_STAMPED so the binary self-identifies via
#     --version.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

DIRTY_FILES="$(git status --porcelain)"
DIRTY_SUFFIX=""
if [ -n "$DIRTY_FILES" ]; then
    DIRTY_SUFFIX="-dirty"
    if [ "${MEMTERM_ALLOW_DIRTY:-0}" != "1" ]; then
        echo "make-app.sh: REFUSING to build from a dirty tree (set MEMTERM_ALLOW_DIRTY=1 to force a -dirty-stamped build):" >&2
        echo "$DIRTY_FILES" >&2
        exit 1
    fi
    echo "make-app.sh: WARNING dirty tree — artifact will be stamped -dirty" >&2
fi

GIT_HASH="$(git rev-parse --short HEAD)$DIRTY_SUFFIX"
GIT_COUNT="$(git rev-list --count HEAD)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
# Release builds (release.yml) pass the tag's version; local builds stamp
# 0.1.<commit count>. CFBundleVersion stays the commit count either way —
# numeric and monotonic, which is what Sparkle compares.
SHORT_VERSION="${MEMTERM_VERSION:-0.1.$GIT_COUNT}"
# Sparkle self-update (Updater.swift): the appcast every release publishes,
# and the EdDSA public key its DMG signatures verify against (private half:
# the SPARKLE_PRIVATE_KEY Actions secret; keychain item on the founder's Mac).
SPARKLE_FEED_URL="${MEMTERM_SPARKLE_FEED:-https://github.com/ril3y/memterm/releases/latest/download/appcast.xml}"
SPARKLE_PUBLIC_KEY="oylrv6N1LwQaMXjT3mSLlWlk49DtlpUqExStT2++Sac="
# Code-signing identity. A STABLE identity matters beyond Gatekeeper: macOS
# ties Accessibility / Input Monitoring grants to the app's designated
# requirement, and an ad-hoc signature's is the hash of that exact binary —
# every update silently invalidated the grant the drop-down's double-tap
# needs (founder 2026-09-10). MEMTERM_SIGN_IDENTITY overrides; otherwise the
# first of Developer ID Application / Apple Development in the keychain;
# else ad-hoc ("-").
if [ -z "${MEMTERM_SIGN_IDENTITY:-}" ]; then
    IDS="$(security find-identity -v -p codesigning 2>/dev/null || true)"
    for kind in "Developer ID Application" "Apple Development"; do
        cand="$(printf '%s\n' "$IDS" | grep -oE "\"$kind: [^\"]+\"" | head -1 | tr -d '"' || true)"
        if [ -n "$cand" ]; then MEMTERM_SIGN_IDENTITY="$cand"; break; fi
    done
    MEMTERM_SIGN_IDENTITY="${MEMTERM_SIGN_IDENTITY:--}"
fi

STAMP_FILE="$REPO_ROOT/Sources/memterm/BuildStamp.generated.swift"
cat > "$STAMP_FILE" <<STAMP
// Generated by scripts/make-app.sh — DO NOT EDIT, DO NOT COMMIT (gitignored).
enum GeneratedBuildStamp {
    static let version = "$SHORT_VERSION"
    static let gitHash = "$GIT_HASH"
    static let buildTimeUTC = "$BUILD_TIME"
}
STAMP

swift build -c release -Xswiftc -DMEMTERM_STAMPED >&2

APP_DIR="$REPO_ROOT/dist/memterm.app"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources" "$APP_DIR/Contents/Frameworks"

cp "$REPO_ROOT/.build/release/memterm" "$APP_DIR/Contents/MacOS/memterm"
# Sparkle.framework (SwiftPM binary target) rides in Contents/Frameworks; the
# binary links it via @rpath, so give it the standard app rpath.
cp -R "$REPO_ROOT/.build/release/Sparkle.framework" "$APP_DIR/Contents/Frameworks/Sparkle.framework"
install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_DIR/Contents/MacOS/memterm" 2>/dev/null || true
cp "$REPO_ROOT/Assets/memterm.icns" "$APP_DIR/Contents/Resources/memterm.icns"
# Help ▸ memterm README opens this bundled copy (council #6 menu hygiene).
cp "$REPO_ROOT/README.md" "$APP_DIR/Contents/Resources/README.md"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>com.memterm.app</string>
	<key>CFBundleName</key>
	<string>memterm</string>
	<key>CFBundleExecutable</key>
	<string>memterm</string>
	<key>CFBundleIconFile</key>
	<string>memterm</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$SHORT_VERSION</string>
	<key>CFBundleVersion</key>
	<string>$GIT_COUNT</string>
	<key>MemtermGitHash</key>
	<string>$GIT_HASH</string>
	<key>MemtermBuildTimeUTC</key>
	<string>$BUILD_TIME</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>LSMultipleInstancesProhibited</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>14.0</string>
	<key>SUFeedURL</key>
	<string>$SPARKLE_FEED_URL</string>
	<key>SUPublicEDKey</key>
	<string>$SPARKLE_PUBLIC_KEY</string>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUScheduledCheckInterval</key>
	<integer>86400</integer>
</dict>
</plist>
PLIST

# Signing, inside-out (Sparkle's nested Autoupdate/XPC bundles first, then
# the framework, then the app — never --deep over the app), all with the
# same identity so the nested requirements agree.
SIGN=(codesign --force --timestamp=none --sign "$MEMTERM_SIGN_IDENTITY")
"${SIGN[@]}" "$APP_DIR/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc" >&2 2>/dev/null || true
"${SIGN[@]}" "$APP_DIR/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc" >&2 2>/dev/null || true
"${SIGN[@]}" "$APP_DIR/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate" >&2
"${SIGN[@]}" "$APP_DIR/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app" >&2
"${SIGN[@]}" "$APP_DIR/Contents/Frameworks/Sparkle.framework" >&2
"${SIGN[@]}" "$APP_DIR" >&2
echo "make-app.sh: signed with ${MEMTERM_SIGN_IDENTITY} — $(codesign -d -r- "$APP_DIR" 2>&1 | grep designated | cut -c1-140)" >&2

# Artifact identity = embedded stamp + POST-codesign binary hash (codesign
# mutates the binary, so .build/release hashes can never match — record dist).
echo "make-app.sh: stamp $SHORT_VERSION ($GIT_HASH) built $BUILD_TIME" >&2
echo "make-app.sh: sha256(post-codesign) $(shasum -a 256 "$APP_DIR/Contents/MacOS/memterm" | cut -d' ' -f1)" >&2

echo "$APP_DIR"
